on:
  workflow_dispatch:
  push:
    branches:
      - editor
  pull_request:
    branches:
      - editor

name: Build and deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: editor
          node-version: 18
      - name: Checkout editor repo
        uses: actions/checkout@v4
        with:
          repository: master
          path: master
      - run: |
          npm ci
          npm run run_id
          npm run run_ttl
      - name: Update ttl
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}
          git add .
          git commit -m 'Updating ttl with Github Actions'
          git push origin editor
          git push origin master
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
